Feature branch
S-BLH/cash-register pull request #1
Opened 2024-07-10 10:27 UTC by S-BLH

- created a repo by the name of cash register
- cloned it to my pc
- created html,css and js files
- added the linters
- added html , css and java script codes
- added a design to the code
- cleaned the code

2024-07-10 14:25 UTC, latifa-wakili commented
✔ Created a professional Repo
✔ Correct use of Gitflow 
✔ Commit messages are meaningful
✔ Setup the linters correctly 
✔ No linter errors (All linters checks have been passed 🟢)
✔ Created the pull request 
✔ Good PR description
✔Your code is clean
✔Your repo has a professional README.md file
✔Your design is responsive
keep it up!

2024-07-10 15:18 UTC, S-BLH commented
@ahzamir ostad kindly review my project, as my partner commented and reviewed it already.

2024-07-10 15:26 UTC, ahzamir commented
> ✔ Created a professional Repo ✔ Correct use of Gitflow ✔ Commit messages are meaningful ✔ Setup the linters correctly ✔ No linter errors (All linters checks have been passed 🟢) ✔ Created the pull request ✔ Good PR description ✔Your code is clean ✔Your repo has a professional README.md file ✔Your design is responsive keep it up!

@latifa-wakili 

- Why do you give feedback without checking your partner's code and project there are lots of issues in this project but you approved it.

2024-07-10 15:32 UTC, ahzamir requested changes
@S-BLH 

- Your project has some issus that I will point out please also check the comments below for more required changes:
  - Your project should show the amount of money in different cashes like this [example](https://cash-register.freecodecamp.rocks/):
  - Your design:  
![image](https://github.com/S-BLH/cash-register/assets/96838030/b434d542-8150-4839-9a82-89a413562c82)
  - Freecodecamp design:
![image](https://github.com/S-BLH/cash-register/assets/96838030/c4d973e6-a5cf-4162-b657-c1c2e066e8c2)

2024-07-10 15:32 UTC, ahzamir commented on index.html
> +    </style>
- You have a different file for your CSS codes which is `style.css` and here also you linked a file named `styles.css` please change the name of your `style.css` to `styles.css` and move your CSS code there.

2024-07-10 22:38 UTC, S-BLH commented
@ahzamir Ostad as you said, I changed the whole appearance of the project, and added the numbers to it, kindly review it again.

2024-07-11 08:58 UTC, ahzamir commented
@S-BLH 

- Your project is not responsive and also I can see the total price for the item as shown in the example
- also when I enter a cash value and click on purchase it is not showing me anything

2024-07-11 10:13 UTC, S-BLH commented
@ahzamir OStad did the things you said, kindly review it.

2024-07-12 14:30 UTC, ahzamir commented
@S-BLH 

- Don't mention me again you have to get your partner feedback before mentioning me

2024-07-12 14:33 UTC, S-BLH commented
@ahzamir ostad my partner already commented on this project, she didnt comment on the pokemon project, and also she is not responding right now to my texts,

2024-07-12 15:18 UTC, ahzamir commented
@S-BLH 

- As i said before you have to show everything for the user but I can not see the total piece:

![image](https://github.com/user-attachments/assets/328cb5c4-9691-4733-a5f6-0ff7db7f8c5e)

2024-07-12 15:19 UTC, ahzamir commented
- And also when user add less money than the price you should show the error.

2024-07-13 18:00 UTC, S-BLH commented
@ahzamir Dear Ostad, this time everything is clear and I solved its problem, kindly review it

2024-07-14 14:24 UTC, ahzamir approved these changes
### Hi @S-BLH 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/user-attachments/assets/4a27a6fa-13e9-483c-93e0-f1c7f0f7b766)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

2024-07-14 14:24 UTC, ahzamir commented on index.html
> +    </style>
- I told you in previous comments to separate your styling code from your HTML file as you have a CSS file for them.
- Solve this issue and then directly merge your branch.

2024-07-14 15:27 UTC, merged